export const TOURNAMENT_FORMAT = {
  NO_CATEGORIES: 'NO_CATEGORIES',
  WITH_CATEGORIES: 'WITH_CATEGORIES',
  CATEGORIES_AND_SUBCATEGORIES: 'CATEGORIES_AND_SUBCATEGORIES'
}

export const TOURNAMENT_STATUS = {
  CREATED: 'CREATED',
  REGISTRATION_PHASE: 'REGISTRATION_PHASE',
  PREPARATION_PHASE: 'PREPARATION_PHASE',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  CANCELED: 'CANCELED',
  ARCHIVED: 'ARCHIVED'
}
